### ISSUE TITLE
Can we have this package name on `npm`? 

### ISSUE THREAD

**Issue by indexzero** [robgraeber/winston2#1]
Hi there, author of `winston` here. 

There are ways to accomplish what you are trying to accomplish with `winston@2.x` and **even easier ways in `winston@3.0.0`** which will be released into beta this week.

``` js

var util = require('util');
var winston = require('winston');
var logger = new winston.Logger({
  format: winston.format(function (info, opts) {
    info.raw = util.format('%s: %s %s', info.level, info.message, JSON.stringify(info));
    return info;
  }),
  transports: [new winston.transports.Console()]
});
```

For our benchmarking suites we would like to have published:
- `winston1`: `winston@1.1.2` for historical benchmarking purposes
- `winston2`: `winston@2.1.1` for historical benchmarking purposes

Would you consider donating the name `winston2` to the `winston` project?

**Comment by robgraeber** [comment]
Hey I saw your message and I'll let you know later tonight

**Comment by robgraeber** [comment]
Hey sorry I'm inclined to say no because I like/use my module a lot (I think the console.log format should be default) and an historical library for benchmarking seems pretty minor. 

Maybe you can call the benchmarking libs "winston-v1" / "winston-v2", I think that would be more straight forward.

**Comment by indexzero** [comment]
@robgraeber we'll just use the `winston1x` naming, but still disappointed you wouldn't go out of your way to support the projects you use. Open source is about more than consuming and publishing. It's about giving back. Hopefully you will learn this in time. Regardless a couple of facts you should be ware of:
1. Upgrade to use `winston@2.x` (and eventually `winston@3.x` in a few weeks) They are 10-50% faster than `winston@1.x` which you are currently using.
2. Your statement _"I think the console.log format should be default"_ is just patently false since this one of the formats supported by default.

**Comment by robgraeber** [comment]
How is console.log format supported by default? And don't appreciate the guilt trip, if you had a better use I'd be with you. For a benchmarking lib.. ¯\_(ツ)_/¯

**Comment by indexzero** [comment]
See documentation on [string interpolation](https://github.com/winstonjs/winston#string-interpolation) which is what `console.log` uses under the covers.
